### PR TITLE
Phone visualisation

### PR DESCRIPTION
**Pull request by mattheworiordan**
@CrowdHailer please see the updates below.  To be honest, too many to mention in this PR, best you simply browser through the commits themselves and review givitalob.com.

We are doing a demo today with giveitalob, but following that I believe we still need to do the following:
- A design and copy review - I'm getting someone to take a look and smarten things up a little, especially on home / track / fly pages
- Throw detection is still not right.  I reworked your implementation as once the throws were being shown in the graph and I added a sound for each lob, it became clear that you were in fact detecting multiple throws for each throw.  My implementation is not right either yet, but is getting close.

My bug bears with this project currently are:
- Asset compilation requires it to be done locally and committed.  It makes the commit history messy and really is unnecessary.  Unfortunately, I cannot get ES6 transpiling to work with Sinatra and asset compilation, so I have stopped as I don't want to waste any more time on this
- The javascript generally is framework like, but not.  There is so much boiler plate code and mixing of concerns that it's hard to maintain.  This is just a demo so not worth fixing, but it's far from ideal unfortunately. Case in point [tracker app](https://github.com/CrowdHailer/lob/blob/master/client/tracker.js), has a [tracker showcase](https://github.com/CrowdHailer/lob/blob/master/client/tracker/showcase.js), with the [view back in the tracker app](https://github.com/CrowdHailer/lob/blob/master/client/tracker.js#L121-L154), which has another [tracker thing](https://github.com/CrowdHailer/lob/blob/master/client/tracker/tracker.js).

PS. Tests are broken.  I don't see the point in keeping this test coverage updated personally given this is a "lab" project and demo.

I am doing this PR so that you can see the changes, but I will probably just run with this fork now unless you want to do something different.  Grab me on Slack when you have a chance.

### CODE REVIEW

**Comment by CrowdHailer** [comment]
Hi thats all good,

The tests were there when I developed but got commented out when they were unhelpful. No real need to keep them. I was toying with the idea of the code base itself being part of a valuable demo but I don't think that is the case any more.

Whats your current mechanism for throw detection? I had found measuring zero g times quite reliable but thought it might be improved by having a minimum time. so a really short zero g period would not trigger a throw.

The asset compilation is a bug bear certainly. I was hoping that it might be possible to run this site as a static page and too keep all data in the Ably system when I originally developed. As I understand it that is not possible.

Probably won't find a time on slack this week. But I have a train journey soon so will look through the code changes. I like what you have done with the styling btw

**Comment by mattheworiordan** [comment]
Hi Peter

On a plane so please ignore the reply via email.

Some quick comments below:

> The tests were there when I developed but got commented out when they were unhelpful. No real need to keep them. I was toying with the idea of the code base itself being part of a valuable demo but I don't think that is the case any more.
> 
> You’ll see that we now have this repo at https://github.com/ably/lob https://github.com/ably/lob which is now the definitive place we’ll keep our work going.  You’ll also see that I got the server tests running and passing again, but binned the front end tests.
> Whats your current mechanism for throw detection? I had found measuring zero g times quite reliable but thought it might be improved by having a minimum time. so a really short zero g period would not trigger a throw.
> 
> The throw detection needed quite a bit of tweaking, but essentially I detect the curve indicating that it’s accelerating up, then decelerating, then stationery, and then in freefall.  Whilst your detection seemed to work well, the problem was that it was registering multiple throws.  This was not obvious when we were not charting the throws over the x/y/z graphs, but once I did, I saw that happen most of the time.  The other problem with negative magnitude detection is that it could also indicate some waving the phone, or lowering it quickly before throwing it up.  In the end, you’ll see in the code, I had to implement curve detection and some noise reduction to filter out false positives.
> The asset compilation is a bug bear certainly. I was hoping that it might be possible to run this site as a static page and too keep all data in the Ably system when I originally developed. As I understand it that is not possible.
> 
> Yup, pretty unlikely, especially given things like channel names are generated server-side.  In fact, I’ve now even added a checksum to avoid people intentionally creating offensive channel names or hijacking channels.
> Probably won't find a time on slack this week. But I have a train journey soon so will look through the code changes. I like what you have done with the styling btw
> 
> Glad you like it, we’re hoping to get some major styling improvements next week in fact.  We’ll be in touch before any official launch btw.

Thanks,
Matt

**Comment by CrowdHailer** [comment]
Hi Matt,

Just a quick catchup message since I haven't heard any more from you recently. The ably repository is now the source of development on this project so I was expecting to hear from you if there was anything else you needed from me. Regarding copy I think that was being left in your hands, as a developer I wasn't going to bring much sparkle to the mission statement for ably.

I have a few dormant projects which I am trying to clean up. If possible I would just like to confirm that there is nothing you are waiting on from my end.

I will then remove myself from the Ably slack team. I get the odd @channel message once in a while which dont mean anything to me anymore.

Enjoyed the Ably news letter. I hope business is going well.

**Comment by mattheworiordan** [comment]
>  The ably repository is now the source of development on this project so I was expecting to hear from you if there was anything else you needed from me.

Yup, sorry, we delayed things as we wanted a nicer skin.  We've done that, and I should release that in the coming days.  

> Regarding copy I think that was being left in your hands, as a developer I wasn't going to bring much sparkle to the mission statement for ably.

Yup, I'm going to hand over to Ashley to review!

> I have a few dormant projects which I am trying to clean up. If possible I would just like to confirm that there is nothing you are waiting on from my end.

Nope, all good.

> I will then remove myself from the Ably slack team. I get the odd @channel message once in a while which dont mean anything to me anymore.

Sounds good.

> Enjoyed the Ably news letter. I hope business is going well.

Yup, good, and busy!  Same for you too I hope.

I'll send you an email in regards to Lob updates and our launch plan, so closing this issue for now

**Comment by mattheworiordan** [comment]
@CrowdHailer FYI, see https://github.com/ably/giveitalob/pull/2, and http://www.giveitalob.com.  If you have any feedback or comments I'd appreciate it.  We expect to go live and promote within 2 weeks

**Pull request closed without merging**
